---
version: 2.1

orbs:
  ansible-lint: orbss/ansible-lint@0.0.3
  trailing-whitespace: orbss/trailing-whitespace@0.0.2
  yamllint: orbss/yamllint@0.0.4

parameters:
  ansible_lint_executor_image:
    type: string
    default: ghcr.io/docker-images-mamono210/circleci-executors/ansible-lint:26.1.1-py3.14
  ansible_lint_executor_resource_class:
    type: enum
    enum: [small, medium, medium+, large]
    default: small
  molecule_docker_executor_image:
    type: string
    default: ghcr.io/docker-images-mamono210/circleci-executors/molecule-docker:26.2.0-py3.14-ans13.4.0
  molecule_machine_executor_image:
    type: string
    default: ubuntu-2204:2023.10.1
  molecule_machine_executor_resource_class:
    type: enum
    enum: [medium, large, xlarge]
    default: medium
  trailing_whitespace_executor_image:
    type: string
    default: ghcr.io/docker-images-mamono210/circleci-executors/trailing-whitespace:py3.14-20260210
  trailing_whitespace_executor_resource_class:
    type: enum
    enum: [small, medium, medium+, large]
    default: small
  yamllint_executor_image:
    type: string
    default: ghcr.io/docker-images-mamono210/circleci-executors/yamllint:1.38.0-py3.14
  yamllint_executor_resource_class:
    type: enum
    enum: [small, medium, medium+, large]
    default: small

jobs:
  ansible-lint:
    executor:
      name: ansible-lint/default
      image: << pipeline.parameters.ansible_lint_executor_image >>
      resource_class: << pipeline.parameters.ansible_lint_executor_resource_class >>
    steps:
      - checkout
      - ansible-lint/execute:
          molecule-role-test: true
  molecule:
    machine:
      image: << pipeline.parameters.molecule_machine_executor_image >>
      resource_class: << pipeline.parameters.molecule_machine_executor_resource_class >>
    parameters:
      checkout-path:
        type: string
      molecule-docker-executor-image:
        type: string
      molecule-scenario-name:
        type: string
      molecule-test-image:
        type: string
    steps:
      - checkout:
          path: << parameters.checkout-path >>
      - run:
          name: Test with Molecule
          command: |
            sudo chmod 666 /var/run/docker.sock

            cd << parameters.checkout-path >>

            docker run --rm -it \
            -e ANSIBLE_FORCE_COLOR=1 \
            -e MOLECULE_IMAGE=<< parameters.molecule-test-image >> \
            -v "$(pwd)":/tmp/$(basename "${PWD}"):ro \
            -v /usr/bin/docker:/usr/bin/docker \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -w /tmp/$(basename "${PWD}") \
            << parameters.molecule-docker-executor-image >> \
            molecule test --scenario-name << parameters.molecule-scenario-name >>
      - run:
          name: Show Ansible version
          command: |
            docker run --rm -it \
            << parameters.molecule-docker-executor-image >> \
            ansible --version \
            | GREP_COLORS='mt=01;34' egrep --color=always '[[:digit:]]' \
            | GREP_COLORS='mt=01;34' egrep --color=always '\.' \
            | GREP_COLORS='mt=01;33' egrep --color=always 'ansible.* '
      - run:
          name: Show Molecule version
          command: |
            docker run --rm -it \
            << parameters.molecule-docker-executor-image >> \
            molecule --version
  trailing-whitespace:
    executor:
      name: trailing-whitespace/default
      image: << pipeline.parameters.trailing_whitespace_executor_image >>
      resource_class: << pipeline.parameters.trailing_whitespace_executor_resource_class >>
    steps:
      - checkout
      - trailing-whitespace/execute
  yamllint:
    executor:
      name: yamllint/default
      image: << pipeline.parameters.yamllint_executor_image >>
      resource_class: << pipeline.parameters.yamllint_executor_resource_class >>
    steps:
      - checkout
      - yamllint/execute

workflows:
  version: 2.1
  build:
    jobs:
      - trailing-whitespace
      - yamllint:
          requires:
            - trailing-whitespace
      - ansible-lint:
          requires:
            - yamllint
      - molecule:
          matrix:
            parameters:
              checkout-path:
                - 'vim_install'
              molecule-docker-executor-image:
                - '<< pipeline.parameters.molecule_docker_executor_image >>'
              molecule-scenario-name:
                - 'default'
              molecule-test-image:
                - 'ghcr.io/docker-images-mamono210/ansible-test/centos-stream9:latest'
          requires:
            - ansible-lint
